services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306 # Map host_port:container_port
    command: --init-file /data/application/init.sql
    volumes:
        - mysql-data:/var/lib/mysql
        - ./init.sql:/data/application/init.sql

volumes:
  mysql-data: